// autogenerated at 2026-10-04T02:05:23.6875969+02:00
import type { ICoreCoreLoginRequest, ICoreCoreRegisterUserRequest, ICoreCoreRegisterUserResponse, ICoreCoreUserProfileResponse } from "./aquatrader_coreTypes";
import { baseUrl } from "./config";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

/**
* function core.login(
*     _scheme character varying,
*     _username character varying,
*     _password character varying
* )
* returns table(
*     scheme character varying,
*     user_id bigint,
*     organisation_id bigint,
*     username character varying,
*     roles text[],
*     email character varying,
*     password_hash text
* )
* 
* @remarks
* comment on function core.login is 'HTTP POST
* login
* sensitive
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
* 
* @see FUNCTION core.login
*/
export async function coreCoreLogin(
    request: ICoreCoreLoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/core/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function core.register_user(
*     _username character varying,
*     _full_name character varying,
*     _billing_address text,
*     _email character varying,
*     _password character varying,
*     _password_hash text,
*     _phone_number character varying
* )
* returns table(
*     user_id bigint
* )
* 
* @remarks
* comment on function core.register_user is 'HTTP POST
* param _password_hash is hash of _password
* sensitive
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ICoreCoreRegisterUserResponse[]>}
* 
* @see FUNCTION core.register_user
*/
export async function coreCoreRegisterUser(
    request: ICoreCoreRegisterUserRequest
) : Promise<ApiResult<ICoreCoreRegisterUserResponse[]>> {
    const response = await fetch(baseUrl + "/api/core/register-user", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICoreCoreRegisterUserResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function core.user_profile()
* returns table(
*     organisation_id bigint,
*     billing_name character varying,
*     billing_email character varying,
*     user_id bigint,
*     username character varying,
*     roles text[],
*     email character varying
* )
* 
* @remarks
* comment on function core.user_profile is 'HTTP GET
* sensitive
* authenticated';
* 
* @returns {ApiResult<ICoreCoreUserProfileResponse[]>}
* 
* @see FUNCTION core.user_profile
*/
export async function coreCoreUserProfile() : Promise<ApiResult<ICoreCoreUserProfileResponse[]>> {
    const response = await fetch(baseUrl + "/api/core/user-profile", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICoreCoreUserProfileResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}
