// autogenerated at 2026-10-04T02:05:24.8063524+02:00
export interface ITechnicalTechnicalIndicatorconfigurationsIndicatoridRequest {
    indicatorId?: number | null;
}

export interface ITechnicalTechnicalIndicatorconfigurationsIndicatoridResponse {
    indicatorConfigurationId: number | null;
    indicatorId: number | null;
    indicatorCode: string | null;
    indicatorName: string | null;
    parameters: any; // JSON
}

export interface ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateRequest {
    listingId: number | null;
    indicatorConfigurationId: number | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResponse {
    priceDate: string | null;
    value1: number | null;
    value2: number | null;
    value3: number | null;
    value4: number | null;
}

export interface ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateRequest {
    listingId: number | null;
    indicatorConfigurationId: number | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResponse {
    priceDate: string | null;
    indicatorConfigurationId: number | null;
    indicatorCode: string | null;
    indicatorName: string | null;
    parameters: any; // JSON
    value1: number | null;
    value2: number | null;
    value3: number | null;
    value4: number | null;
}

export interface ITechnicalTechnicalIndicatorsResponse {
    indicatorId: number | null;
    code: string | null;
    name: string | null;
    description: string | null;
    outputCount: number | null;
}

export interface ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateRequest {
    listingId: number | null;
    indicatorConfigurationIds: number[] | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResponse {
    priceDate: string | null;
    indicatorConfigurationId: number | null;
    indicatorCode: string | null;
    indicatorName: string | null;
    parameters: any; // JSON
    value1: number | null;
    value2: number | null;
    value3: number | null;
    value4: number | null;
}

export interface ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsRequest {
    listingId: number | null;
    indicatorConfigurationIds?: number[] | null;
}

export interface ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResponse {
    priceDate: string | null;
    indicatorConfigurationId: number | null;
    indicatorCode: string | null;
    indicatorName: string | null;
    parameters: any; // JSON
    value1: number | null;
    value2: number | null;
    value3: number | null;
    value4: number | null;
}

