// autogenerated at 2026-10-04T02:05:24.8110701+02:00
import {
    useQuery,
    type UseQueryOptions,
} from "@tanstack/react-query";
import * as api from "./aquatrader_technical";

type TechnicalTechnicalIndicatorconfigurationsIndicatoridRequest = Parameters<typeof api.technicalTechnicalIndicatorconfigurationsIndicatorid>[0];
type TechnicalTechnicalIndicatorconfigurationsIndicatoridResult = Awaited<ReturnType<typeof api.technicalTechnicalIndicatorconfigurationsIndicatorid>>;

export const technicalTechnicalIndicatorconfigurationsIndicatoridKeys = {
    all: ["technicalTechnicalIndicatorconfigurationsIndicatorid"] as const,
    byRequest: (request: TechnicalTechnicalIndicatorconfigurationsIndicatoridRequest) =>
        ["technicalTechnicalIndicatorconfigurationsIndicatorid", request] as const,
};

export function useTechnicalTechnicalIndicatorconfigurationsIndicatorid(
    request: TechnicalTechnicalIndicatorconfigurationsIndicatoridRequest,
    options?: Omit<
        UseQueryOptions<TechnicalTechnicalIndicatorconfigurationsIndicatoridResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: technicalTechnicalIndicatorconfigurationsIndicatoridKeys.byRequest(request),
        queryFn: () => api.technicalTechnicalIndicatorconfigurationsIndicatorid(request),
        ...options,
    });
}

type TechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateRequest = Parameters<typeof api.technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate>[0];
type TechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResult = Awaited<ReturnType<typeof api.technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate>>;

export const technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateKeys = {
    all: ["technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate"] as const,
    byRequest: (request: TechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateRequest) =>
        ["technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate", request] as const,
};

export function useTechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate(
    request: TechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateRequest,
    options?: Omit<
        UseQueryOptions<TechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateKeys.byRequest(request),
        queryFn: () => api.technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate(request),
        ...options,
    });
}

type TechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateRequest = Parameters<typeof api.technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate>[0];
type TechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResult = Awaited<ReturnType<typeof api.technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate>>;

export const technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateKeys = {
    all: ["technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate"] as const,
    byRequest: (request: TechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateRequest) =>
        ["technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate", request] as const,
};

export function useTechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate(
    request: TechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateRequest,
    options?: Omit<
        UseQueryOptions<TechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateKeys.byRequest(request),
        queryFn: () => api.technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate(request),
        ...options,
    });
}

type TechnicalTechnicalIndicatorsResult = Awaited<ReturnType<typeof api.technicalTechnicalIndicators>>;

export const technicalTechnicalIndicatorsKeys = {
    all: ["technicalTechnicalIndicators"] as const,
};

export function useTechnicalTechnicalIndicators(
    options?: Omit<
        UseQueryOptions<TechnicalTechnicalIndicatorsResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: technicalTechnicalIndicatorsKeys.all,
        queryFn: () => api.technicalTechnicalIndicators(),
        ...options,
    });
}

type TechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateRequest = Parameters<typeof api.technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate>[0];
type TechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResult = Awaited<ReturnType<typeof api.technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate>>;

export const technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateKeys = {
    all: ["technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate"] as const,
    byRequest: (request: TechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateRequest) =>
        ["technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate", request] as const,
};

export function useTechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate(
    request: TechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateRequest,
    options?: Omit<
        UseQueryOptions<TechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateKeys.byRequest(request),
        queryFn: () => api.technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate(request),
        ...options,
    });
}

type TechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsRequest = Parameters<typeof api.technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids>[0];
type TechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResult = Awaited<ReturnType<typeof api.technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids>>;

export const technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsKeys = {
    all: ["technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids"] as const,
    byRequest: (request: TechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsRequest) =>
        ["technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids", request] as const,
};

export function useTechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids(
    request: TechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsRequest,
    options?: Omit<
        UseQueryOptions<TechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsKeys.byRequest(request),
        queryFn: () => api.technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids(request),
        ...options,
    });
}
