// autogenerated at 2026-10-04T02:05:24.8082855+02:00
import type { ITechnicalTechnicalIndicatorconfigurationsIndicatoridRequest, ITechnicalTechnicalIndicatorconfigurationsIndicatoridResponse, ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateRequest, ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResponse, ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateRequest, ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResponse, ITechnicalTechnicalIndicatorsResponse, ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateRequest, ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResponse, ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsRequest, ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResponse } from "./aquatrader_technicalTypes";
import { baseUrl } from "./config";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

/**
* function technical.get_indicator_configurations(
*     _indicator_id smallint DEFAULT NULL::smallint
* )
* returns table(
*     indicator_configuration_id bigint,
*     indicator_id smallint,
*     indicator_code character varying,
*     indicator_name character varying,
*     parameters jsonb
* )
* 
* @remarks
* comment on function technical.get_indicator_configurations is '  HTTP GET /api/technical/indicatorconfigurations/{indicatorId}
*   anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ITechnicalTechnicalIndicatorconfigurationsIndicatoridResponse[]>}
* 
* @see FUNCTION technical.get_indicator_configurations
*/
export async function technicalTechnicalIndicatorconfigurationsIndicatorid(
    request: ITechnicalTechnicalIndicatorconfigurationsIndicatoridRequest
) : Promise<ApiResult<ITechnicalTechnicalIndicatorconfigurationsIndicatoridResponse[]>> {
    const response = await fetch(`${baseUrl}/api/technical/indicatorconfigurations/${request.indicatorId}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ITechnicalTechnicalIndicatorconfigurationsIndicatoridResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function technical.get_indicator_eod(
*     _listing_id bigint,
*     _indicator_configuration_id bigint,
*     _from_date date,
*     _to_date date
* )
* returns table(
*     price_date date,
*     value_1 double precision,
*     value_2 double precision,
*     value_3 double precision,
*     value_4 double precision
* )
* 
* @remarks
* comment on function technical.get_indicator_eod is 'HTTP GET /api/technical/indicatoreod/{listingId}/{indicatorConfigurationId}/{fromDate}/{toDate}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResponse[]>}
* 
* @see FUNCTION technical.get_indicator_eod
*/
export async function technicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodate(
    request: ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateRequest
) : Promise<ApiResult<ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/technical/indicatoreod/${request.listingId}/${request.indicatorConfigurationId}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ITechnicalTechnicalIndicatoreodListingidIndicatorconfigurationidFromdateTodateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function technical.get_indicator_eod_series(
*     _listing_id bigint,
*     _indicator_configuration_id bigint,
*     _from_date date,
*     _to_date date
* )
* returns table(
*     price_date date,
*     indicator_configuration_id bigint,
*     indicator_code character varying,
*     indicator_name character varying,
*     parameters jsonb,
*     value_1 double precision,
*     value_2 double precision,
*     value_3 double precision,
*     value_4 double precision
* )
* 
* @remarks
* comment on function technical.get_indicator_eod_series is 'HTTP GET /api/technical/indicatoreodseries/{listingId}/{indicatorConfigurationId}/{fromDate}/{toDate}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResponse[]>}
* 
* @see FUNCTION technical.get_indicator_eod_series
*/
export async function technicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodate(
    request: ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateRequest
) : Promise<ApiResult<ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/technical/indicatoreodseries/${request.listingId}/${request.indicatorConfigurationId}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ITechnicalTechnicalIndicatoreodseriesListingidIndicatorconfigurationidFromdateTodateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function technical.get_indicators()
* returns table(
*     indicator_id smallint,
*     code character varying,
*     name character varying,
*     description text,
*     output_count smallint
* )
* 
* @remarks
* comment on function technical.get_indicators is 'HTTP GET /api/technical/indicators
* anonymous';
* 
* @returns {ApiResult<ITechnicalTechnicalIndicatorsResponse[]>}
* 
* @see FUNCTION technical.get_indicators
*/
export async function technicalTechnicalIndicators() : Promise<ApiResult<ITechnicalTechnicalIndicatorsResponse[]>> {
    const response = await fetch(baseUrl + "/api/technical/indicators", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ITechnicalTechnicalIndicatorsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function technical.get_indicators_eod_series(
*     _listing_id bigint,
*     _indicator_configuration_ids bigint[],
*     _from_date date,
*     _to_date date
* )
* returns table(
*     price_date date,
*     indicator_configuration_id bigint,
*     indicator_code character varying,
*     indicator_name character varying,
*     parameters jsonb,
*     value_1 double precision,
*     value_2 double precision,
*     value_3 double precision,
*     value_4 double precision
* )
* 
* @remarks
* comment on function technical.get_indicators_eod_series is 'HTTP GET /api/technical/indicatorseodseries/{listingId}/{indicatorConfigurationIds}/{fromDate}/{toDate}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResponse[]>}
* 
* @see FUNCTION technical.get_indicators_eod_series
*/
export async function technicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodate(
    request: ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateRequest
) : Promise<ApiResult<ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/technical/indicatorseodseries/${request.listingId}/${request.indicatorConfigurationIds}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ITechnicalTechnicalIndicatorseodseriesListingidIndicatorconfigurationidsFromdateTodateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function technical.get_latest_indicator_values(
*     _listing_id bigint,
*     _indicator_configuration_ids bigint[] DEFAULT NULL::bigint[]
* )
* returns table(
*     price_date date,
*     indicator_configuration_id bigint,
*     indicator_code character varying,
*     indicator_name character varying,
*     parameters jsonb,
*     value_1 double precision,
*     value_2 double precision,
*     value_3 double precision,
*     value_4 double precision
* )
* 
* @remarks
* comment on function technical.get_latest_indicator_values is 'HTTP GET /api/technical/latestindicatorvalues/{listingId}/{indicatorConfigurationIds}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResponse[]>}
* 
* @see FUNCTION technical.get_latest_indicator_values
*/
export async function technicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationids(
    request: ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsRequest
) : Promise<ApiResult<ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResponse[]>> {
    const response = await fetch(`${baseUrl}/api/technical/latestindicatorvalues/${request.listingId}/${request.indicatorConfigurationIds}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ITechnicalTechnicalLatestindicatorvaluesListingidIndicatorconfigurationidsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}
