// autogenerated at 2026-10-04T02:05:24.1383919+02:00
import {
    useQuery,
    useMutation,
    type UseQueryOptions,
    type UseMutationOptions,
} from "@tanstack/react-query";
import * as api from "./aquatrader_core";

type CoreCoreLoginRequest = Parameters<typeof api.coreCoreLogin>[0];
type CoreCoreLoginResult = Awaited<ReturnType<typeof api.coreCoreLogin>>;

export function useCoreCoreLoginMutation(
    options?: Omit<
        UseMutationOptions<CoreCoreLoginResult, unknown, CoreCoreLoginRequest>,
        "mutationFn"
    >,
) {
    return useMutation({
        mutationFn: (request: CoreCoreLoginRequest) => api.coreCoreLogin(request),
        ...options,
    });
}

type CoreCoreRegisterUserRequest = Parameters<typeof api.coreCoreRegisterUser>[0];
type CoreCoreRegisterUserResult = Awaited<ReturnType<typeof api.coreCoreRegisterUser>>;

export function useCoreCoreRegisterUserMutation(
    options?: Omit<
        UseMutationOptions<CoreCoreRegisterUserResult, unknown, CoreCoreRegisterUserRequest>,
        "mutationFn"
    >,
) {
    return useMutation({
        mutationFn: (request: CoreCoreRegisterUserRequest) => api.coreCoreRegisterUser(request),
        ...options,
    });
}

type CoreCoreUserProfileResult = Awaited<ReturnType<typeof api.coreCoreUserProfile>>;

export const coreCoreUserProfileKeys = {
    all: ["coreCoreUserProfile"] as const,
};

export function useCoreCoreUserProfile(
    options?: Omit<
        UseQueryOptions<CoreCoreUserProfileResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: coreCoreUserProfileKeys.all,
        queryFn: () => api.coreCoreUserProfile(),
        ...options,
    });
}
