// autogenerated at 2026-09-24T22:03:39.1616421+02:00
import type { IPricesPricesEodListingidFromdateTodateRequest, IPricesPricesEodListingidFromdateTodateResponse, IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateRequest, IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResponse, IPricesPricesIntradayListingidFromtimeTotimeRequest, IPricesPricesIntradayListingidFromtimeTotimeResponse, IPricesPricesEodLatestListingidRequest, IPricesPricesEodLatestListingidResponse, IPricesPricesEodLatestListingidLimitLimitRequest, IPricesPricesEodLatestListingidLimitLimitResponse, IPricesPricesFxLatestBasecurrencyQuotecurrencyRequest, IPricesPricesFxLatestBasecurrencyQuotecurrencyResponse, IPricesPricesIntradayLatestListingidRequest, IPricesPricesIntradayLatestListingidResponse, IPricesPricesMarketSnapshotListingIdsListingIdsRequest, IPricesPricesMarketSnapshotListingIdsListingIdsResponse, IPricesPricesDetaileodListingidFromdateTodateRequest, IPricesPricesDetaileodListingidFromdateTodateResponse } from "./aquatrader_pricesTypes";
import { baseUrl } from "./config";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

/**
* function prices.get_eod(
*     _listing_id bigint,
*     _from_date date,
*     _to_date date
* )
* returns table(
*     price_date date,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     adjusted_close numeric,
*     volume numeric,
*     trade_count bigint
* )
* 
* @remarks
* comment on function prices.get_eod is 'HTTP GET /api/prices/eod/{listingId}/{fromDate}/{toDate}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesEodListingidFromdateTodateResponse[]>}
* 
* @see FUNCTION prices.get_eod
*/
export async function pricesPricesEodListingidFromdateTodate(
    request: IPricesPricesEodListingidFromdateTodateRequest
) : Promise<ApiResult<IPricesPricesEodListingidFromdateTodateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/eod/${request.listingId}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesEodListingidFromdateTodateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_fx_eod(
*     _base_currency character varying,
*     _quote_currency character varying,
*     _from_date date,
*     _to_date date
* )
* returns table(
*     price_date date,
*     base_currency character varying,
*     quote_currency character varying,
*     rate numeric
* )
* 
* @remarks
* comment on function prices.get_fx_eod is 'HTTP GET /api/prices/fx/eod/{baseCurrency}/{quoteCurrency}/{fromDate}/{toDate}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResponse[]>}
* 
* @see FUNCTION prices.get_fx_eod
*/
export async function pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate(
    request: IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateRequest
) : Promise<ApiResult<IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/fx/eod/${request.baseCurrency}/${request.quoteCurrency}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_intraday(
*     _listing_id bigint,
*     _from_time timestamp with time zone,
*     _to_time timestamp with time zone
* )
* returns table(
*     price_time timestamp with time zone,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     volume numeric,
*     trade_count bigint
* )
* 
* @remarks
* comment on function prices.get_intraday is 'HTTP GET /api/prices/intraday/{listingId}/{fromTime}/{toTime}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesIntradayListingidFromtimeTotimeResponse[]>}
* 
* @see FUNCTION prices.get_intraday
*/
export async function pricesPricesIntradayListingidFromtimeTotime(
    request: IPricesPricesIntradayListingidFromtimeTotimeRequest
) : Promise<ApiResult<IPricesPricesIntradayListingidFromtimeTotimeResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/intraday/${request.listingId}/${request.fromTime}/${request.toTime}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesIntradayListingidFromtimeTotimeResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_latest_eod(
*     _listing_id bigint
* )
* returns table(
*     listing_id bigint,
*     price_date date,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     adjusted_close numeric,
*     volume numeric,
*     trade_count bigint
* )
* 
* @remarks
* comment on function prices.get_latest_eod is 'HTTP GET /api/prices/eod/latest/{listingId}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesEodLatestListingidResponse[]>}
* 
* @see FUNCTION prices.get_latest_eod
*/
export async function pricesPricesEodLatestListingid(
    request: IPricesPricesEodLatestListingidRequest
) : Promise<ApiResult<IPricesPricesEodLatestListingidResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/eod/latest/${request.listingId}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesEodLatestListingidResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_latest_eod_prices(
*     _listing_id bigint,
*     _limit integer DEFAULT 200
* )
* returns table(
*     price_date date,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     adjusted_close numeric,
*     volume numeric
* )
* 
* @remarks
* comment on function prices.get_latest_eod_prices is 'HTTP GET /api/prices/eod/latest/{listingId}/limit/{limit}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesEodLatestListingidLimitLimitResponse[]>}
* 
* @see FUNCTION prices.get_latest_eod_prices
*/
export async function pricesPricesEodLatestListingidLimitLimit(
    request: IPricesPricesEodLatestListingidLimitLimitRequest
) : Promise<ApiResult<IPricesPricesEodLatestListingidLimitLimitResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/eod/latest/${request.listingId}/limit/${request.limit}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesEodLatestListingidLimitLimitResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_latest_fx(
*     _base_currency character varying,
*     _quote_currency character varying
* )
* returns table(
*     price_date date,
*     base_currency character varying,
*     quote_currency character varying,
*     rate numeric
* )
* 
* @remarks
* comment on function prices.get_latest_fx is 'HTTP GET /api/prices/fx/latest/{baseCurrency}/{quoteCurrency}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesFxLatestBasecurrencyQuotecurrencyResponse[]>}
* 
* @see FUNCTION prices.get_latest_fx
*/
export async function pricesPricesFxLatestBasecurrencyQuotecurrency(
    request: IPricesPricesFxLatestBasecurrencyQuotecurrencyRequest
) : Promise<ApiResult<IPricesPricesFxLatestBasecurrencyQuotecurrencyResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/fx/latest/${request.baseCurrency}/${request.quoteCurrency}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesFxLatestBasecurrencyQuotecurrencyResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_latest_intraday(
*     _listing_id bigint
* )
* returns table(
*     price_time timestamp with time zone,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     volume numeric,
*     trade_count bigint
* )
* 
* @remarks
* comment on function prices.get_latest_intraday is 'HTTP GET /api/prices/intraday/latest/{listingId}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesIntradayLatestListingidResponse[]>}
* 
* @see FUNCTION prices.get_latest_intraday
*/
export async function pricesPricesIntradayLatestListingid(
    request: IPricesPricesIntradayLatestListingidRequest
) : Promise<ApiResult<IPricesPricesIntradayLatestListingidResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/intraday/latest/${request.listingId}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesIntradayLatestListingidResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_latest_market_snapshot(
*     _listing_ids bigint[]
* )
* returns table(
*     listing_id bigint,
*     price_date date,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     adjusted_close numeric,
*     volume numeric
* )
* 
* @remarks
* comment on function prices.get_latest_market_snapshot is 'HTTP GET /api/prices/market-snapshot/listing_ids/{listing_ids}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesMarketSnapshotListingIdsListingIdsResponse[]>}
* 
* @see FUNCTION prices.get_latest_market_snapshot
*/
export async function pricesPricesMarketSnapshotListingIdsListingIds(
    request: IPricesPricesMarketSnapshotListingIdsListingIdsRequest
) : Promise<ApiResult<IPricesPricesMarketSnapshotListingIdsListingIdsResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/market-snapshot/listing_ids/${request.listingIds}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesMarketSnapshotListingIdsListingIdsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function prices.get_listing_eod(
*     _listing_id bigint,
*     _from_date date,
*     _to_date date
* )
* returns table(
*     listing_id bigint,
*     symbol character varying,
*     instrument_name character varying,
*     exchange_name character varying,
*     currency_code character varying,
*     price_date date,
*     open numeric,
*     high numeric,
*     low numeric,
*     close numeric,
*     adjusted_close numeric,
*     volume numeric
* )
* 
* @remarks
* comment on function prices.get_listing_eod is 'HTTP GET /api/prices/detaileod/{listingId}/{fromDate}/{toDate}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPricesPricesDetaileodListingidFromdateTodateResponse[]>}
* 
* @see FUNCTION prices.get_listing_eod
*/
export async function pricesPricesDetaileodListingidFromdateTodate(
    request: IPricesPricesDetaileodListingidFromdateTodateRequest
) : Promise<ApiResult<IPricesPricesDetaileodListingidFromdateTodateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/prices/detaileod/${request.listingId}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPricesPricesDetaileodListingidFromdateTodateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}
