// autogenerated at 2026-10-04T02:05:24.5943389+02:00
import type { IMarketCurrenciesResponse, IMarketCurrenciesIdRequest, IMarketCurrenciesIdResponse, IMarketExchangesIdRequest, IMarketExchangesIdResponse, IMarketExchangesResponse, IMarketInstrumentsIdRequest, IMarketInstrumentsIdResponse, IMarketInstrumentsPagePagePagesizePageSizeRequest, IMarketInstrumentsPagePagePagesizePageSizeResponse, IMarketListingsIdRequest, IMarketListingsIdResponse, IMarketListingsOverviewListingidRequest, IMarketListingsOverviewListingidResponse, IMarketListingsResponse, IMarketExchangesTradingSessionsExchangeIdFromDateToDateRequest, IMarketExchangesTradingSessionsExchangeIdFromDateToDateResponse, IMarketInstrumentsSearchQueryQueryPagesizePagesizeRequest, IMarketInstrumentsSearchQueryQueryPagesizePagesizeResponse, IMarketListingsSearchQueryQueryPagesizePagesizeRequest, IMarketListingsSearchQueryQueryPagesizePagesizeResponse } from "./aquatrader_marketTypes";
import { baseUrl } from "./config";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

/**
* function market.get_currencies()
* returns table(
*     id smallint,
*     code character varying,
*     name character varying,
*     symbol character varying,
*     decimal_places smallint,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_currencies is 'HTTP GET /api/currencies
* anonymous';
* 
* @returns {ApiResult<IMarketCurrenciesResponse[]>}
* 
* @see FUNCTION market.get_currencies
*/
export async function marketCurrencies() : Promise<ApiResult<IMarketCurrenciesResponse[]>> {
    const response = await fetch(baseUrl + "/api/currencies", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketCurrenciesResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_currency(
*     _id smallint
* )
* returns table(
*     id smallint,
*     code character varying,
*     name character varying,
*     symbol character varying,
*     decimal_places smallint,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_currency is 'HTTP GET /api/currencies/{id}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketCurrenciesIdResponse[]>}
* 
* @see FUNCTION market.get_currency
*/
export async function marketCurrenciesId(
    request: IMarketCurrenciesIdRequest
) : Promise<ApiResult<IMarketCurrenciesIdResponse[]>> {
    const response = await fetch(`${baseUrl}/api/currencies/${request.id}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketCurrenciesIdResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_exchange(
*     _id integer
* )
* returns table(
*     id integer,
*     name character varying,
*     short_name character varying,
*     mic character varying,
*     operating_mic character varying,
*     country_code character varying,
*     timezone character varying,
*     website character varying,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_exchange is 'HTTP GET /api/exchanges/{id}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketExchangesIdResponse[]>}
* 
* @see FUNCTION market.get_exchange
*/
export async function marketExchangesId(
    request: IMarketExchangesIdRequest
) : Promise<ApiResult<IMarketExchangesIdResponse[]>> {
    const response = await fetch(`${baseUrl}/api/exchanges/${request.id}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketExchangesIdResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_exchanges()
* returns table(
*     id integer,
*     name character varying,
*     short_name character varying,
*     mic character varying,
*     operating_mic character varying,
*     country_code character varying,
*     timezone character varying,
*     website character varying,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_exchanges is 'HTTP GET /api/exchanges
* anonymous';
* 
* @returns {ApiResult<IMarketExchangesResponse[]>}
* 
* @see FUNCTION market.get_exchanges
*/
export async function marketExchanges() : Promise<ApiResult<IMarketExchangesResponse[]>> {
    const response = await fetch(baseUrl + "/api/exchanges", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketExchangesResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_instrument(
*     _id bigint
* )
* returns table(
*     id bigint,
*     isin character varying,
*     name character varying,
*     instrument_type character varying,
*     country_of_origin character varying,
*     sector character varying,
*     industry character varying,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_instrument is 'HTTP GET /api/instruments/{id}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketInstrumentsIdResponse[]>}
* 
* @see FUNCTION market.get_instrument
*/
export async function marketInstrumentsId(
    request: IMarketInstrumentsIdRequest
) : Promise<ApiResult<IMarketInstrumentsIdResponse[]>> {
    const response = await fetch(`${baseUrl}/api/instruments/${request.id}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketInstrumentsIdResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_instruments(
*     _page integer DEFAULT 1,
*     _page_size integer DEFAULT 50
* )
* returns table(
*     id bigint,
*     isin character varying,
*     name character varying,
*     instrument_type character varying,
*     country_of_origin character varying,
*     sector character varying,
*     industry character varying,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_instruments is 'HTTP GET /api/instruments/page/{page}/pagesize/{page_size}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketInstrumentsPagePagePagesizePageSizeResponse[]>}
* 
* @see FUNCTION market.get_instruments
*/
export async function marketInstrumentsPagePagePagesizePageSize(
    request: IMarketInstrumentsPagePagePagesizePageSizeRequest
) : Promise<ApiResult<IMarketInstrumentsPagePagePagesizePageSizeResponse[]>> {
    const response = await fetch(`${baseUrl}/api/instruments/page/${request.page}/pagesize/${request.pageSize}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketInstrumentsPagePagePagesizePageSizeResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_listing(
*     _id bigint
* )
* returns table(
*     id bigint,
*     instrument_id bigint,
*     instrument_name character varying,
*     isin character varying,
*     exchange_id integer,
*     exchange_name character varying,
*     mic character varying,
*     currency_id smallint,
*     currency_code character varying,
*     symbol character varying,
*     local_symbol character varying,
*     listing_type character varying,
*     first_trade_date date,
*     last_trade_date date,
*     is_primary boolean,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_listing is 'HTTP GET /api/listings/{id}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketListingsIdResponse[]>}
* 
* @see FUNCTION market.get_listing
*/
export async function marketListingsId(
    request: IMarketListingsIdRequest
) : Promise<ApiResult<IMarketListingsIdResponse[]>> {
    const response = await fetch(`${baseUrl}/api/listings/${request.id}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketListingsIdResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_listing_overview(
*     _listing_id bigint
* )
* returns table(
*     listing_id bigint,
*     instrument_id bigint,
*     instrument_name character varying,
*     isin character varying,
*     instrument_type character varying,
*     symbol character varying,
*     exchange_id integer,
*     exchange_name character varying,
*     mic character varying,
*     currency_id smallint,
*     currency_code character varying,
*     currency_symbol character varying,
*     country_code character varying,
*     sector character varying,
*     industry character varying,
*     first_trade_date date,
*     last_trade_date date,
*     is_primary boolean
* )
* 
* @remarks
* comment on function market.get_listing_overview is 'HTTP GET /api/listings/overview/{listingId}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketListingsOverviewListingidResponse[]>}
* 
* @see FUNCTION market.get_listing_overview
*/
export async function marketListingsOverviewListingid(
    request: IMarketListingsOverviewListingidRequest
) : Promise<ApiResult<IMarketListingsOverviewListingidResponse[]>> {
    const response = await fetch(`${baseUrl}/api/listings/overview/${request.listingId}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketListingsOverviewListingidResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_listings()
* returns table(
*     id bigint,
*     instrument_id bigint,
*     instrument_name character varying,
*     isin character varying,
*     exchange_id integer,
*     exchange_name character varying,
*     mic character varying,
*     currency_id smallint,
*     currency_code character varying,
*     symbol character varying,
*     local_symbol character varying,
*     listing_type character varying,
*     first_trade_date date,
*     last_trade_date date,
*     is_primary boolean,
*     is_active boolean
* )
* 
* @remarks
* comment on function market.get_listings is 'HTTP GET /api/listings
* anonymous';
* 
* @returns {ApiResult<IMarketListingsResponse[]>}
* 
* @see FUNCTION market.get_listings
*/
export async function marketListings() : Promise<ApiResult<IMarketListingsResponse[]>> {
    const response = await fetch(baseUrl + "/api/listings", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketListingsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.get_trading_sessions(
*     _exchange_id integer,
*     _from_date date,
*     _to_date date
* )
* returns table(
*     session_date date,
*     open_time timestamp with time zone,
*     close_time timestamp with time zone,
*     is_trading_day boolean
* )
* 
* @remarks
* comment on function market.get_trading_sessions is 'HTTP GET /api/exchanges/trading-sessions/{exchange_id}/{from_date}/{to_date}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketExchangesTradingSessionsExchangeIdFromDateToDateResponse[]>}
* 
* @see FUNCTION market.get_trading_sessions
*/
export async function marketExchangesTradingSessionsExchangeIdFromDateToDate(
    request: IMarketExchangesTradingSessionsExchangeIdFromDateToDateRequest
) : Promise<ApiResult<IMarketExchangesTradingSessionsExchangeIdFromDateToDateResponse[]>> {
    const response = await fetch(`${baseUrl}/api/exchanges/trading-sessions/${request.exchangeId}/${request.fromDate}/${request.toDate}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketExchangesTradingSessionsExchangeIdFromDateToDateResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.search_instruments(
*     _query text,
*     _page_size integer DEFAULT 50
* )
* returns table(
*     id bigint,
*     isin character varying,
*     name character varying,
*     instrument_type character varying
* )
* 
* @remarks
* comment on function market.search_instruments is 'HTTP GET /api/instruments/search/query/{query}/pagesize/{pageSize}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketInstrumentsSearchQueryQueryPagesizePagesizeResponse[]>}
* 
* @see FUNCTION market.search_instruments
*/
export async function marketInstrumentsSearchQueryQueryPagesizePagesize(
    request: IMarketInstrumentsSearchQueryQueryPagesizePagesizeRequest
) : Promise<ApiResult<IMarketInstrumentsSearchQueryQueryPagesizePagesizeResponse[]>> {
    const response = await fetch(`${baseUrl}/api/instruments/search/query/${request.query}/pagesize/${request.pageSize}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketInstrumentsSearchQueryQueryPagesizePagesizeResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function market.search_listings(
*     _query text,
*     _page_size integer DEFAULT 50
* )
* returns table(
*     listing_id bigint,
*     instrument_id bigint,
*     instrument_name character varying,
*     isin character varying,
*     symbol character varying,
*     exchange_id integer,
*     exchange_name character varying,
*     mic character varying,
*     currency_code character varying,
*     is_primary boolean
* )
* 
* @remarks
* comment on function market.search_listings is 'HTTP GET /api/listings/search/query/{query}/pagesize/{pageSize}
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IMarketListingsSearchQueryQueryPagesizePagesizeResponse[]>}
* 
* @see FUNCTION market.search_listings
*/
export async function marketListingsSearchQueryQueryPagesizePagesize(
    request: IMarketListingsSearchQueryQueryPagesizePagesizeRequest
) : Promise<ApiResult<IMarketListingsSearchQueryQueryPagesizePagesizeResponse[]>> {
    const response = await fetch(`${baseUrl}/api/listings/search/query/${request.query}/pagesize/${request.pageSize}`, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMarketListingsSearchQueryQueryPagesizePagesizeResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}
