// autogenerated at 2026-09-24T22:03:39.1565312+02:00
export interface IMarketCurrenciesResponse {
    id: number | null;
    code: string | null;
    name: string | null;
    symbol: string | null;
    decimalPlaces: number | null;
    isActive: boolean | null;
}

export interface IMarketCurrenciesIdRequest {
    id: number | null;
}

export interface IMarketCurrenciesIdResponse {
    id: number | null;
    code: string | null;
    name: string | null;
    symbol: string | null;
    decimalPlaces: number | null;
    isActive: boolean | null;
}

export interface IMarketExchangesIdRequest {
    id: number | null;
}

export interface IMarketExchangesIdResponse {
    id: number | null;
    name: string | null;
    shortName: string | null;
    mic: string | null;
    operatingMic: string | null;
    countryCode: string | null;
    timezone: string | null;
    website: string | null;
    isActive: boolean | null;
}

export interface IMarketExchangesResponse {
    id: number | null;
    name: string | null;
    shortName: string | null;
    mic: string | null;
    operatingMic: string | null;
    countryCode: string | null;
    timezone: string | null;
    website: string | null;
    isActive: boolean | null;
}

export interface IMarketInstrumentsIdRequest {
    id: number | null;
}

export interface IMarketInstrumentsIdResponse {
    id: number | null;
    isin: string | null;
    name: string | null;
    instrumentType: string | null;
    countryOfOrigin: string | null;
    sector: string | null;
    industry: string | null;
    isActive: boolean | null;
}

export interface IMarketInstrumentsPagePagePagesizePageSizeRequest {
    page?: number | null;
    pageSize?: number | null;
}

export interface IMarketInstrumentsPagePagePagesizePageSizeResponse {
    id: number | null;
    isin: string | null;
    name: string | null;
    instrumentType: string | null;
    countryOfOrigin: string | null;
    sector: string | null;
    industry: string | null;
    isActive: boolean | null;
}

export interface IMarketListingsIdRequest {
    id: number | null;
}

export interface IMarketListingsIdResponse {
    id: number | null;
    instrumentId: number | null;
    instrumentName: string | null;
    isin: string | null;
    exchangeId: number | null;
    exchangeName: string | null;
    mic: string | null;
    currencyId: number | null;
    currencyCode: string | null;
    symbol: string | null;
    localSymbol: string | null;
    listingType: string | null;
    firstTradeDate: string | null;
    lastTradeDate: string | null;
    isPrimary: boolean | null;
    isActive: boolean | null;
}

export interface IMarketListingsOverviewListingidRequest {
    listingId: number | null;
}

export interface IMarketListingsOverviewListingidResponse {
    listingId: number | null;
    instrumentId: number | null;
    instrumentName: string | null;
    isin: string | null;
    instrumentType: string | null;
    symbol: string | null;
    exchangeId: number | null;
    exchangeName: string | null;
    mic: string | null;
    currencyId: number | null;
    currencyCode: string | null;
    currencySymbol: string | null;
    countryCode: string | null;
    sector: string | null;
    industry: string | null;
    firstTradeDate: string | null;
    lastTradeDate: string | null;
    isPrimary: boolean | null;
}

export interface IMarketListingsResponse {
    id: number | null;
    instrumentId: number | null;
    instrumentName: string | null;
    isin: string | null;
    exchangeId: number | null;
    exchangeName: string | null;
    mic: string | null;
    currencyId: number | null;
    currencyCode: string | null;
    symbol: string | null;
    localSymbol: string | null;
    listingType: string | null;
    firstTradeDate: string | null;
    lastTradeDate: string | null;
    isPrimary: boolean | null;
    isActive: boolean | null;
}

export interface IMarketExchangesTradingSessionsExchangeIdFromDateToDateRequest {
    exchangeId: number | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface IMarketExchangesTradingSessionsExchangeIdFromDateToDateResponse {
    sessionDate: string | null;
    openTime: string | null;
    closeTime: string | null;
    isTradingDay: boolean | null;
}

export interface IMarketInstrumentsSearchQueryQueryPagesizePagesizeRequest {
    query: string | null;
    pageSize?: number | null;
}

export interface IMarketInstrumentsSearchQueryQueryPagesizePagesizeResponse {
    id: number | null;
    isin: string | null;
    name: string | null;
    instrumentType: string | null;
}

export interface IMarketListingsSearchQueryQueryPagesizePagesizeRequest {
    query: string | null;
    pageSize?: number | null;
}

export interface IMarketListingsSearchQueryQueryPagesizePagesizeResponse {
    listingId: number | null;
    instrumentId: number | null;
    instrumentName: string | null;
    isin: string | null;
    symbol: string | null;
    exchangeId: number | null;
    exchangeName: string | null;
    mic: string | null;
    currencyCode: string | null;
    isPrimary: boolean | null;
}

