// autogenerated at 2026-10-04T02:05:24.7286051+02:00
import {
    useQuery,
    type UseQueryOptions,
} from "@tanstack/react-query";
import * as api from "./aquatrader_prices";

type PricesPricesEodListingidFromdateTodateRequest = Parameters<typeof api.pricesPricesEodListingidFromdateTodate>[0];
type PricesPricesEodListingidFromdateTodateResult = Awaited<ReturnType<typeof api.pricesPricesEodListingidFromdateTodate>>;

export const pricesPricesEodListingidFromdateTodateKeys = {
    all: ["pricesPricesEodListingidFromdateTodate"] as const,
    byRequest: (request: PricesPricesEodListingidFromdateTodateRequest) =>
        ["pricesPricesEodListingidFromdateTodate", request] as const,
};

export function usePricesPricesEodListingidFromdateTodate(
    request: PricesPricesEodListingidFromdateTodateRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesEodListingidFromdateTodateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesEodListingidFromdateTodateKeys.byRequest(request),
        queryFn: () => api.pricesPricesEodListingidFromdateTodate(request),
        ...options,
    });
}

type PricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateRequest = Parameters<typeof api.pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate>[0];
type PricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResult = Awaited<ReturnType<typeof api.pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate>>;

export const pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateKeys = {
    all: ["pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate"] as const,
    byRequest: (request: PricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateRequest) =>
        ["pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate", request] as const,
};

export function usePricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate(
    request: PricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateKeys.byRequest(request),
        queryFn: () => api.pricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodate(request),
        ...options,
    });
}

type PricesPricesIntradayListingidFromtimeTotimeRequest = Parameters<typeof api.pricesPricesIntradayListingidFromtimeTotime>[0];
type PricesPricesIntradayListingidFromtimeTotimeResult = Awaited<ReturnType<typeof api.pricesPricesIntradayListingidFromtimeTotime>>;

export const pricesPricesIntradayListingidFromtimeTotimeKeys = {
    all: ["pricesPricesIntradayListingidFromtimeTotime"] as const,
    byRequest: (request: PricesPricesIntradayListingidFromtimeTotimeRequest) =>
        ["pricesPricesIntradayListingidFromtimeTotime", request] as const,
};

export function usePricesPricesIntradayListingidFromtimeTotime(
    request: PricesPricesIntradayListingidFromtimeTotimeRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesIntradayListingidFromtimeTotimeResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesIntradayListingidFromtimeTotimeKeys.byRequest(request),
        queryFn: () => api.pricesPricesIntradayListingidFromtimeTotime(request),
        ...options,
    });
}

type PricesPricesEodLatestListingidRequest = Parameters<typeof api.pricesPricesEodLatestListingid>[0];
type PricesPricesEodLatestListingidResult = Awaited<ReturnType<typeof api.pricesPricesEodLatestListingid>>;

export const pricesPricesEodLatestListingidKeys = {
    all: ["pricesPricesEodLatestListingid"] as const,
    byRequest: (request: PricesPricesEodLatestListingidRequest) =>
        ["pricesPricesEodLatestListingid", request] as const,
};

export function usePricesPricesEodLatestListingid(
    request: PricesPricesEodLatestListingidRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesEodLatestListingidResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesEodLatestListingidKeys.byRequest(request),
        queryFn: () => api.pricesPricesEodLatestListingid(request),
        ...options,
    });
}

type PricesPricesEodLatestListingidLimitLimitRequest = Parameters<typeof api.pricesPricesEodLatestListingidLimitLimit>[0];
type PricesPricesEodLatestListingidLimitLimitResult = Awaited<ReturnType<typeof api.pricesPricesEodLatestListingidLimitLimit>>;

export const pricesPricesEodLatestListingidLimitLimitKeys = {
    all: ["pricesPricesEodLatestListingidLimitLimit"] as const,
    byRequest: (request: PricesPricesEodLatestListingidLimitLimitRequest) =>
        ["pricesPricesEodLatestListingidLimitLimit", request] as const,
};

export function usePricesPricesEodLatestListingidLimitLimit(
    request: PricesPricesEodLatestListingidLimitLimitRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesEodLatestListingidLimitLimitResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesEodLatestListingidLimitLimitKeys.byRequest(request),
        queryFn: () => api.pricesPricesEodLatestListingidLimitLimit(request),
        ...options,
    });
}

type PricesPricesFxLatestBasecurrencyQuotecurrencyRequest = Parameters<typeof api.pricesPricesFxLatestBasecurrencyQuotecurrency>[0];
type PricesPricesFxLatestBasecurrencyQuotecurrencyResult = Awaited<ReturnType<typeof api.pricesPricesFxLatestBasecurrencyQuotecurrency>>;

export const pricesPricesFxLatestBasecurrencyQuotecurrencyKeys = {
    all: ["pricesPricesFxLatestBasecurrencyQuotecurrency"] as const,
    byRequest: (request: PricesPricesFxLatestBasecurrencyQuotecurrencyRequest) =>
        ["pricesPricesFxLatestBasecurrencyQuotecurrency", request] as const,
};

export function usePricesPricesFxLatestBasecurrencyQuotecurrency(
    request: PricesPricesFxLatestBasecurrencyQuotecurrencyRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesFxLatestBasecurrencyQuotecurrencyResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesFxLatestBasecurrencyQuotecurrencyKeys.byRequest(request),
        queryFn: () => api.pricesPricesFxLatestBasecurrencyQuotecurrency(request),
        ...options,
    });
}

type PricesPricesIntradayLatestListingidRequest = Parameters<typeof api.pricesPricesIntradayLatestListingid>[0];
type PricesPricesIntradayLatestListingidResult = Awaited<ReturnType<typeof api.pricesPricesIntradayLatestListingid>>;

export const pricesPricesIntradayLatestListingidKeys = {
    all: ["pricesPricesIntradayLatestListingid"] as const,
    byRequest: (request: PricesPricesIntradayLatestListingidRequest) =>
        ["pricesPricesIntradayLatestListingid", request] as const,
};

export function usePricesPricesIntradayLatestListingid(
    request: PricesPricesIntradayLatestListingidRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesIntradayLatestListingidResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesIntradayLatestListingidKeys.byRequest(request),
        queryFn: () => api.pricesPricesIntradayLatestListingid(request),
        ...options,
    });
}

type PricesPricesMarketSnapshotListingIdsListingIdsRequest = Parameters<typeof api.pricesPricesMarketSnapshotListingIdsListingIds>[0];
type PricesPricesMarketSnapshotListingIdsListingIdsResult = Awaited<ReturnType<typeof api.pricesPricesMarketSnapshotListingIdsListingIds>>;

export const pricesPricesMarketSnapshotListingIdsListingIdsKeys = {
    all: ["pricesPricesMarketSnapshotListingIdsListingIds"] as const,
    byRequest: (request: PricesPricesMarketSnapshotListingIdsListingIdsRequest) =>
        ["pricesPricesMarketSnapshotListingIdsListingIds", request] as const,
};

export function usePricesPricesMarketSnapshotListingIdsListingIds(
    request: PricesPricesMarketSnapshotListingIdsListingIdsRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesMarketSnapshotListingIdsListingIdsResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesMarketSnapshotListingIdsListingIdsKeys.byRequest(request),
        queryFn: () => api.pricesPricesMarketSnapshotListingIdsListingIds(request),
        ...options,
    });
}

type PricesPricesDetaileodListingidFromdateTodateRequest = Parameters<typeof api.pricesPricesDetaileodListingidFromdateTodate>[0];
type PricesPricesDetaileodListingidFromdateTodateResult = Awaited<ReturnType<typeof api.pricesPricesDetaileodListingidFromdateTodate>>;

export const pricesPricesDetaileodListingidFromdateTodateKeys = {
    all: ["pricesPricesDetaileodListingidFromdateTodate"] as const,
    byRequest: (request: PricesPricesDetaileodListingidFromdateTodateRequest) =>
        ["pricesPricesDetaileodListingidFromdateTodate", request] as const,
};

export function usePricesPricesDetaileodListingidFromdateTodate(
    request: PricesPricesDetaileodListingidFromdateTodateRequest,
    options?: Omit<
        UseQueryOptions<PricesPricesDetaileodListingidFromdateTodateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: pricesPricesDetaileodListingidFromdateTodateKeys.byRequest(request),
        queryFn: () => api.pricesPricesDetaileodListingidFromdateTodate(request),
        ...options,
    });
}
