// autogenerated at 2026-10-04T02:05:24.6976509+02:00
export interface IPricesPricesEodListingidFromdateTodateRequest {
    listingId: number | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface IPricesPricesEodListingidFromdateTodateResponse {
    priceDate: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    adjustedClose: number | null;
    volume: number | null;
    tradeCount: number | null;
}

export interface IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateRequest {
    baseCurrency: string | null;
    quoteCurrency: string | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface IPricesPricesFxEodBasecurrencyQuotecurrencyFromdateTodateResponse {
    priceDate: string | null;
    baseCurrency: string | null;
    quoteCurrency: string | null;
    rate: number | null;
}

export interface IPricesPricesIntradayListingidFromtimeTotimeRequest {
    listingId: number | null;
    fromTime: string | null;
    toTime: string | null;
}

export interface IPricesPricesIntradayListingidFromtimeTotimeResponse {
    priceTime: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    volume: number | null;
    tradeCount: number | null;
}

export interface IPricesPricesEodLatestListingidRequest {
    listingId: number | null;
}

export interface IPricesPricesEodLatestListingidResponse {
    listingId: number | null;
    priceDate: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    adjustedClose: number | null;
    volume: number | null;
    tradeCount: number | null;
}

export interface IPricesPricesEodLatestListingidLimitLimitRequest {
    listingId: number | null;
    limit?: number | null;
}

export interface IPricesPricesEodLatestListingidLimitLimitResponse {
    priceDate: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    adjustedClose: number | null;
    volume: number | null;
}

export interface IPricesPricesFxLatestBasecurrencyQuotecurrencyRequest {
    baseCurrency: string | null;
    quoteCurrency: string | null;
}

export interface IPricesPricesFxLatestBasecurrencyQuotecurrencyResponse {
    priceDate: string | null;
    baseCurrency: string | null;
    quoteCurrency: string | null;
    rate: number | null;
}

export interface IPricesPricesIntradayLatestListingidRequest {
    listingId: number | null;
}

export interface IPricesPricesIntradayLatestListingidResponse {
    priceTime: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    volume: number | null;
    tradeCount: number | null;
}

export interface IPricesPricesMarketSnapshotListingIdsListingIdsRequest {
    listingIds: number[] | null;
}

export interface IPricesPricesMarketSnapshotListingIdsListingIdsResponse {
    listingId: number | null;
    priceDate: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    adjustedClose: number | null;
    volume: number | null;
}

export interface IPricesPricesDetaileodListingidFromdateTodateRequest {
    listingId: number | null;
    fromDate: string | null;
    toDate: string | null;
}

export interface IPricesPricesDetaileodListingidFromdateTodateResponse {
    listingId: number | null;
    symbol: string | null;
    instrumentName: string | null;
    exchangeName: string | null;
    currencyCode: string | null;
    priceDate: string | null;
    open: number | null;
    high: number | null;
    low: number | null;
    close: number | null;
    adjustedClose: number | null;
    volume: number | null;
}

