// autogenerated at 2026-10-04T02:05:24.6552018+02:00
import {
    useQuery,
    type UseQueryOptions,
} from "@tanstack/react-query";
import * as api from "./aquatrader_market";

type MarketCurrenciesResult = Awaited<ReturnType<typeof api.marketCurrencies>>;

export const marketCurrenciesKeys = {
    all: ["marketCurrencies"] as const,
};

export function useMarketCurrencies(
    options?: Omit<
        UseQueryOptions<MarketCurrenciesResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketCurrenciesKeys.all,
        queryFn: () => api.marketCurrencies(),
        ...options,
    });
}

type MarketCurrenciesIdRequest = Parameters<typeof api.marketCurrenciesId>[0];
type MarketCurrenciesIdResult = Awaited<ReturnType<typeof api.marketCurrenciesId>>;

export const marketCurrenciesIdKeys = {
    all: ["marketCurrenciesId"] as const,
    byRequest: (request: MarketCurrenciesIdRequest) =>
        ["marketCurrenciesId", request] as const,
};

export function useMarketCurrenciesId(
    request: MarketCurrenciesIdRequest,
    options?: Omit<
        UseQueryOptions<MarketCurrenciesIdResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketCurrenciesIdKeys.byRequest(request),
        queryFn: () => api.marketCurrenciesId(request),
        ...options,
    });
}

type MarketExchangesIdRequest = Parameters<typeof api.marketExchangesId>[0];
type MarketExchangesIdResult = Awaited<ReturnType<typeof api.marketExchangesId>>;

export const marketExchangesIdKeys = {
    all: ["marketExchangesId"] as const,
    byRequest: (request: MarketExchangesIdRequest) =>
        ["marketExchangesId", request] as const,
};

export function useMarketExchangesId(
    request: MarketExchangesIdRequest,
    options?: Omit<
        UseQueryOptions<MarketExchangesIdResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketExchangesIdKeys.byRequest(request),
        queryFn: () => api.marketExchangesId(request),
        ...options,
    });
}

type MarketExchangesResult = Awaited<ReturnType<typeof api.marketExchanges>>;

export const marketExchangesKeys = {
    all: ["marketExchanges"] as const,
};

export function useMarketExchanges(
    options?: Omit<
        UseQueryOptions<MarketExchangesResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketExchangesKeys.all,
        queryFn: () => api.marketExchanges(),
        ...options,
    });
}

type MarketInstrumentsIdRequest = Parameters<typeof api.marketInstrumentsId>[0];
type MarketInstrumentsIdResult = Awaited<ReturnType<typeof api.marketInstrumentsId>>;

export const marketInstrumentsIdKeys = {
    all: ["marketInstrumentsId"] as const,
    byRequest: (request: MarketInstrumentsIdRequest) =>
        ["marketInstrumentsId", request] as const,
};

export function useMarketInstrumentsId(
    request: MarketInstrumentsIdRequest,
    options?: Omit<
        UseQueryOptions<MarketInstrumentsIdResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketInstrumentsIdKeys.byRequest(request),
        queryFn: () => api.marketInstrumentsId(request),
        ...options,
    });
}

type MarketInstrumentsPagePagePagesizePageSizeRequest = Parameters<typeof api.marketInstrumentsPagePagePagesizePageSize>[0];
type MarketInstrumentsPagePagePagesizePageSizeResult = Awaited<ReturnType<typeof api.marketInstrumentsPagePagePagesizePageSize>>;

export const marketInstrumentsPagePagePagesizePageSizeKeys = {
    all: ["marketInstrumentsPagePagePagesizePageSize"] as const,
    byRequest: (request: MarketInstrumentsPagePagePagesizePageSizeRequest) =>
        ["marketInstrumentsPagePagePagesizePageSize", request] as const,
};

export function useMarketInstrumentsPagePagePagesizePageSize(
    request: MarketInstrumentsPagePagePagesizePageSizeRequest,
    options?: Omit<
        UseQueryOptions<MarketInstrumentsPagePagePagesizePageSizeResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketInstrumentsPagePagePagesizePageSizeKeys.byRequest(request),
        queryFn: () => api.marketInstrumentsPagePagePagesizePageSize(request),
        ...options,
    });
}

type MarketListingsIdRequest = Parameters<typeof api.marketListingsId>[0];
type MarketListingsIdResult = Awaited<ReturnType<typeof api.marketListingsId>>;

export const marketListingsIdKeys = {
    all: ["marketListingsId"] as const,
    byRequest: (request: MarketListingsIdRequest) =>
        ["marketListingsId", request] as const,
};

export function useMarketListingsId(
    request: MarketListingsIdRequest,
    options?: Omit<
        UseQueryOptions<MarketListingsIdResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketListingsIdKeys.byRequest(request),
        queryFn: () => api.marketListingsId(request),
        ...options,
    });
}

type MarketListingsOverviewListingidRequest = Parameters<typeof api.marketListingsOverviewListingid>[0];
type MarketListingsOverviewListingidResult = Awaited<ReturnType<typeof api.marketListingsOverviewListingid>>;

export const marketListingsOverviewListingidKeys = {
    all: ["marketListingsOverviewListingid"] as const,
    byRequest: (request: MarketListingsOverviewListingidRequest) =>
        ["marketListingsOverviewListingid", request] as const,
};

export function useMarketListingsOverviewListingid(
    request: MarketListingsOverviewListingidRequest,
    options?: Omit<
        UseQueryOptions<MarketListingsOverviewListingidResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketListingsOverviewListingidKeys.byRequest(request),
        queryFn: () => api.marketListingsOverviewListingid(request),
        ...options,
    });
}

type MarketListingsResult = Awaited<ReturnType<typeof api.marketListings>>;

export const marketListingsKeys = {
    all: ["marketListings"] as const,
};

export function useMarketListings(
    options?: Omit<
        UseQueryOptions<MarketListingsResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketListingsKeys.all,
        queryFn: () => api.marketListings(),
        ...options,
    });
}

type MarketExchangesTradingSessionsExchangeIdFromDateToDateRequest = Parameters<typeof api.marketExchangesTradingSessionsExchangeIdFromDateToDate>[0];
type MarketExchangesTradingSessionsExchangeIdFromDateToDateResult = Awaited<ReturnType<typeof api.marketExchangesTradingSessionsExchangeIdFromDateToDate>>;

export const marketExchangesTradingSessionsExchangeIdFromDateToDateKeys = {
    all: ["marketExchangesTradingSessionsExchangeIdFromDateToDate"] as const,
    byRequest: (request: MarketExchangesTradingSessionsExchangeIdFromDateToDateRequest) =>
        ["marketExchangesTradingSessionsExchangeIdFromDateToDate", request] as const,
};

export function useMarketExchangesTradingSessionsExchangeIdFromDateToDate(
    request: MarketExchangesTradingSessionsExchangeIdFromDateToDateRequest,
    options?: Omit<
        UseQueryOptions<MarketExchangesTradingSessionsExchangeIdFromDateToDateResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketExchangesTradingSessionsExchangeIdFromDateToDateKeys.byRequest(request),
        queryFn: () => api.marketExchangesTradingSessionsExchangeIdFromDateToDate(request),
        ...options,
    });
}

type MarketInstrumentsSearchQueryQueryPagesizePagesizeRequest = Parameters<typeof api.marketInstrumentsSearchQueryQueryPagesizePagesize>[0];
type MarketInstrumentsSearchQueryQueryPagesizePagesizeResult = Awaited<ReturnType<typeof api.marketInstrumentsSearchQueryQueryPagesizePagesize>>;

export const marketInstrumentsSearchQueryQueryPagesizePagesizeKeys = {
    all: ["marketInstrumentsSearchQueryQueryPagesizePagesize"] as const,
    byRequest: (request: MarketInstrumentsSearchQueryQueryPagesizePagesizeRequest) =>
        ["marketInstrumentsSearchQueryQueryPagesizePagesize", request] as const,
};

export function useMarketInstrumentsSearchQueryQueryPagesizePagesize(
    request: MarketInstrumentsSearchQueryQueryPagesizePagesizeRequest,
    options?: Omit<
        UseQueryOptions<MarketInstrumentsSearchQueryQueryPagesizePagesizeResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketInstrumentsSearchQueryQueryPagesizePagesizeKeys.byRequest(request),
        queryFn: () => api.marketInstrumentsSearchQueryQueryPagesizePagesize(request),
        ...options,
    });
}

type MarketListingsSearchQueryQueryPagesizePagesizeRequest = Parameters<typeof api.marketListingsSearchQueryQueryPagesizePagesize>[0];
type MarketListingsSearchQueryQueryPagesizePagesizeResult = Awaited<ReturnType<typeof api.marketListingsSearchQueryQueryPagesizePagesize>>;

export const marketListingsSearchQueryQueryPagesizePagesizeKeys = {
    all: ["marketListingsSearchQueryQueryPagesizePagesize"] as const,
    byRequest: (request: MarketListingsSearchQueryQueryPagesizePagesizeRequest) =>
        ["marketListingsSearchQueryQueryPagesizePagesize", request] as const,
};

export function useMarketListingsSearchQueryQueryPagesizePagesize(
    request: MarketListingsSearchQueryQueryPagesizePagesizeRequest,
    options?: Omit<
        UseQueryOptions<MarketListingsSearchQueryQueryPagesizePagesizeResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: marketListingsSearchQueryQueryPagesizePagesizeKeys.byRequest(request),
        queryFn: () => api.marketListingsSearchQueryQueryPagesizePagesize(request),
        ...options,
    });
}
