// autogenerated at 2026-09-24T22:03:39.1530185+02:00
export interface ICoreCoreLoginRequest {
    scheme: string | null;
    username: string | null;
    password: string | null;
}

export interface ICoreCoreRegisterUserRequest {
    username: string | null;
    fullName: string | null;
    billingAddress: string | null;
    email: string | null;
    password: string | null;
    passwordHash: string | null;
    phoneNumber: string | null;
}

export interface ICoreCoreRegisterUserResponse {
    userId: number | null;
}

export interface ICoreCoreUserProfileResponse {
    organisationId: number | null;
    billingName: string | null;
    billingEmail: string | null;
    userId: number | null;
    username: string | null;
    roles: string[] | null;
    email: string | null;
}

