<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FacioQuo.Stock.Indicators" Version="3.0.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Npgsql.Json.NET" Version="10.0.3" />
    <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechnicalAnalysis.Application\TechnicalAnalysis.Application.csproj" />
  </ItemGroup>

</Project>
