@host=http://localhost:8080

// function staging.csv_upload(
//     _meta json DEFAULT NULL::json
// )
// returns json
//
// comment on function staging.csv_upload is 'HTTP POST
// @authorize
// @upload for csv
// @param _meta is upload metadata
// @delimiters = ,;
// @row_command = select staging.csv_upload_row($1,$2,$3,$4)';
POST {{host}}/api/staging/csv-upload?meta=%7B%7D

###

